FROM alpine-jdk:base
MAINTAINER para-ett
COPY files/free-days-service-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/free-days-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8040