FROM alpine-jdk:base
MAINTAINER para-ett
COPY files/timesheet-records-service-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/timesheet-records-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8060