FROM alpine-jdk:base
MAINTAINER para-ett
COPY files/spring-cloud-configuration-server-0.0.1-SNAPSHOT.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/spring-cloud-configuration-server-0.0.1-SNAPSHOT.jar"]
VOLUME /var/lib/config-repo
EXPOSE 8888