CREATE DATABASE IF NOT EXISTS 'users_db';
CREATE DATABASE IF NOT EXISTS 'free_days_db';
CREATE DATABASE IF NOT EXISTS 'requests_db';
CREATE DATABASE IF NOT EXISTS 'timesheet_records_db';
CREATE DATABASE IF NOT EXISTS 'companies_db';